package com.zhupeng.test.mybatisGenerator.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 * cl_app_proclamation公告
 * @author 朱朋 
 * @date 2019-04-03
 */
@ApiModel(value = "公告")
public class AppProclamation implements Serializable {
    /**
     * 
     */
    @ApiModelProperty(value = "" , name = "id" , example = "" , required = true , dataType = "Integer" ,notes = "")
    private Integer id;

    /**
     * 公告标题
     */
    @ApiModelProperty(value = "公告标题" , name = "title" , example = "" , required = false , dataType = "String" ,notes = "公告标题")
    private String title;

    /**
     * 公告名称
     */
    @ApiModelProperty(value = "公告名称" , name = "name" , example = "" , required = false , dataType = "String" ,notes = "公告名称")
    private String name;

    /**
     * 状态0未启用1启用
     */
    @ApiModelProperty(value = "状态0未启用1启用" , name = "status" , example = "" , required = false , dataType = "String" ,notes = "状态0未启用1启用")
    private String status;

    /**
     * 类型 1：h5 2:原生 
     */
    @ApiModelProperty(value = "类型 1：h5 2:原生 " , name = "type" , example = "" , required = false , dataType = "String" ,notes = "类型 1：h5 2:原生 ")
    private String type;

    /**
     * 描述
     */
    @ApiModelProperty(value = "描述" , name = "describe" , example = "" , required = false , dataType = "String" ,notes = "描述")
    private String describe;

    /**
     * 创建时间
     */
    @ApiModelProperty(value = "创建时间" , name = "createTime" , example = "" , required = false , dataType = "Date" ,notes = "创建时间")
    private Date createTime;

    /**
     * 更新时间
     */
    @ApiModelProperty(value = "更新时间" , name = "updateTime" , example = "" , required = false , dataType = "Date" ,notes = "更新时间")
    private Date updateTime;

    /**
     * 商户编号
     */
    @ApiModelProperty(value = "商户编号" , name = "merchantCode" , example = "" , required = true , dataType = "String" ,notes = "商户编号")
    private String merchantCode;

    /**
     * 备注
     */
    @ApiModelProperty(value = "备注" , name = "remakes" , example = "" , required = false , dataType = "String" ,notes = "备注")
    private String remakes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_app_proclamation
     *
     * @mbg.generated 2019-04-03
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @return id 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 
     * @param id 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 公告标题
     * @return title 公告标题
     */
    public String getTitle() {
        return title;
    }

    /**
     * 公告标题
     * @param title 公告标题
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 公告名称
     * @return name 公告名称
     */
    public String getName() {
        return name;
    }

    /**
     * 公告名称
     * @param name 公告名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 状态0未启用1启用
     * @return status 状态0未启用1启用
     */
    public String getStatus() {
        return status;
    }

    /**
     * 状态0未启用1启用
     * @param status 状态0未启用1启用
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 类型 1：h5 2:原生 
     * @return type 类型 1：h5 2:原生 
     */
    public String getType() {
        return type;
    }

    /**
     * 类型 1：h5 2:原生 
     * @param type 类型 1：h5 2:原生 
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 描述
     * @return describe 描述
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * 描述
     * @param describe 描述
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * 创建时间
     * @return create_time 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 创建时间
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 更新时间
     * @return update_time 更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 更新时间
     * @param updateTime 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 商户编号
     * @return merchant_code 商户编号
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * 商户编号
     * @param merchantCode 商户编号
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode == null ? null : merchantCode.trim();
    }

    /**
     * 备注
     * @return remakes 备注
     */
    public String getRemakes() {
        return remakes;
    }

    /**
     * 备注
     * @param remakes 备注
     */
    public void setRemakes(String remakes) {
        this.remakes = remakes == null ? null : remakes.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", name=").append(name);
        sb.append(", status=").append(status);
        sb.append(", type=").append(type);
        sb.append(", describe=").append(describe);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", merchantCode=").append(merchantCode);
        sb.append(", remakes=").append(remakes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}