package com.zhupeng.baseframe.entity.db;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

/**
 * permission
 * @author 朱朋 
 * @date 2019-06-01
 */
@ApiModel(value = "")
public class Permission implements Serializable {
    /**
     * 
     */
    @ApiModelProperty(value = "" , name = "pid" , example = "" , required = true , dataType = "Integer" ,notes = "")
    private Integer pid;

    /**
     * 权限名称
     */
    @ApiModelProperty(value = "权限名称" , name = "pname" , example = "" , required = false , dataType = "String" ,notes = "权限名称")
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission
     *
     * @mbg.generated 2019-06-01
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @return pid 
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * 
     * @param pid 
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * 权限名称
     * @return pname 权限名称
     */
    public String getPname() {
        return pname;
    }

    /**
     * 权限名称
     * @param pname 权限名称
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", pname=").append(pname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}