package com.zhupeng.baseframe.entity.db;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

/**
 * permission_role
 * @author 朱朋 
 * @date 2019-06-01
 */
@ApiModel(value = "")
public class PermissionRole implements Serializable {
    /**
     * 
     */
    @ApiModelProperty(value = "" , name = "rid" , example = "" , required = true , dataType = "Integer" ,notes = "")
    private Integer rid;

    /**
     * 
     */
    @ApiModelProperty(value = "" , name = "pid" , example = "" , required = true , dataType = "Integer" ,notes = "")
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission_role
     *
     * @mbg.generated 2019-06-01
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @return rid 
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * 
     * @param rid 
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * 
     * @return pid 
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * 
     * @param pid 
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", pid=").append(pid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}