package com.zhupeng.baseframe.entity.db;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

/**
 * role
 * @author 朱朋 
 * @date 2019-06-01
 */
@ApiModel(value = "")
public class Role implements Serializable {
    /**
     * 
     */
    @ApiModelProperty(value = "" , name = "rid" , example = "" , required = true , dataType = "Integer" ,notes = "")
    private Integer rid;

    /**
     * 
     */
    @ApiModelProperty(value = "" , name = "rname" , example = "" , required = false , dataType = "String" ,notes = "")
    private String rname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated 2019-06-01
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @return rid 
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * 
     * @param rid 
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * 
     * @return rname 
     */
    public String getRname() {
        return rname;
    }

    /**
     * 
     * @param rname 
     */
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", rname=").append(rname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}