package com.zhupeng.baseframe.entity.db;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

/**
 * user_role
 * @author 朱朋 
 * @date 2019-06-01
 */
@ApiModel(value = "")
public class UserRole implements Serializable {
    /**
     * 
     */
    @ApiModelProperty(value = "" , name = "uid" , example = "" , required = true , dataType = "Integer" ,notes = "")
    private Integer uid;

    /**
     * 
     */
    @ApiModelProperty(value = "" , name = "rid" , example = "" , required = true , dataType = "Integer" ,notes = "")
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_role
     *
     * @mbg.generated 2019-06-01
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @return uid 
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * 
     * @param uid 
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * 
     * @return rid 
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * 
     * @param rid 
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", rid=").append(rid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}